[nginx-immich-auth]
enabled = true
port = http,https
filter = nginx-immich-auth
logpath = /var/log/nginx/access.log
maxretry = 5
findtime = 300
bantime = 3600
ignoreip = 127.0.0.1/8 ::1 192.168.0.0/16
action = iptables-multiport[name=immich-auth, port="http,https", protocol=tcp]

[nginx-immich-limit]
enabled = true
port = http,https
filter = nginx-immich-limit
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 60
bantime = 600
ignoreip = 127.0.0.1/8 ::1 192.168.0.0/16
action = iptables-multiport[name=immich-limit, port="http,https", protocol=tcp]
